Add random jitter to scan and join delay to appear more natural
depthbomb/Scraps pull request #61
Opened 2023-02-26 11:47 UTC by Mircoxi

Hello! This is a small change to RaffleService to add some minor randomisation to the delays, after a friend of mine suggested it. 

Simply put, it varies how often it scans by up to 60 seconds each time, and raffle join frequency by up to 10 seconds, effectively turning. This has two benefits:

- It looks more natural in any server-side logs, and;
- It more accurately reflects the current climate of the site - raffles tend to be only a few per hour now, so scanning every 5 seconds is just overkill. 

No other changes are made other than this, but it seems like it could be useful so I figured I'd throw a PR in rather than keep it as an offshoot. Thanks!

2023-02-26 18:18 UTC, depthbomb requested changes
This is a good idea, however it should be an opt-in feature that the user can turn on in their settings.

2023-02-26 18:18 UTC, depthbomb commented on Scraps/Services/RaffleService.cs
> +                System.Random _randomifier = new System.Random();
A single System.Random instance should be a private field on the service instance.

2023-02-26 18:18 UTC, depthbomb commented on Scraps/Services/RaffleService.cs
> +                int _scanDelayJittered = _scanDelay + _modifier;
Reserve underscore-prefixed variable names for private field names.

2023-02-28 14:37 UTC, Mircoxi commented
Thanks for the feedback! I've made these changes now, and I've set the default for the jitter options to be zero to make it opt-in. I also took the liberty of adjusting the default window size to accomodate the extra fields and fixed up the TabIndexes since they were a little out of whack. Let me know if anything else needs adjusting!

2023-02-28 17:41 UTC, depthbomb approved these changes

2023-02-28 17:54 UTC, merged